# Generated by Django 2.0.7 on 2018-08-21 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(blank=True, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('category_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant', models.CharField(blank=True, choices=[('basket compare', 'Basket Compare'), ('bq', 'B&Q'), ('homebase', 'Homebase'), ('screwfix', 'Screwfix'), ('selco', 'Selco'), ('toolstation', 'Toolstation'), ('tradepoint', 'Tradepoint'), ('travis perkins', 'Travis Perkins'), ('wickes', 'Wickes')], max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_sku', models.IntegerField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('master_product', 'master_product'), ('compared_product', 'compared_product')], max_length=50, null=True)),
                ('product_sku_1', models.CharField(blank=True, max_length=250, null=True)),
                ('product_sku_2', models.CharField(blank=True, max_length=250, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=250, null=True)),
                ('product_description', models.CharField(blank=True, max_length=250, null=True)),
                ('product_pack_size', models.CharField(blank=True, max_length=250, null=True)),
                ('product_url', models.CharField(blank=True, max_length=250, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_offer', models.CharField(blank=True, max_length=250, null=True)),
                ('product_slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.ManyToManyField(blank=True, to='products.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_name', models.CharField(blank=True, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('subcategory_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('subcategory_description', models.TextField(blank=True, null=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='items',
            field=models.ManyToManyField(blank=True, to='products.Project_Item'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory'),
        ),
    ]
