# Generated by Django 2.0.7 on 2018-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_project_merchants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
