# Generated by Django 2.0.7 on 2018-07-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_subcategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
