# Generated by Django 2.0.7 on 2018-07-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_subcategory_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bc_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
