# Generated by Django 2.0.7 on 2018-10-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181007_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_item',
            name='name',
            field=models.CharField(default='ITEM', max_length=200),
            preserve_default=False,
        ),
    ]
