# Generated by Django 2.0.7 on 2018-10-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_project_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_item',
            name='item',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.RemoveField(
            model_name='project_item',
            name='project',
        ),
        migrations.AddField(
            model_name='project_item',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Project'),
            preserve_default=False,
        ),
    ]
