# Generated by Django 2.0.7 on 2018-10-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181020_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_item',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_items',
            field=models.ManyToManyField(to='products.Project_Item'),
        ),
    ]
