# Generated by Django 2.0.7 on 2018-10-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181020_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_item',
            name='name',
        ),
    ]
