# Generated by Django 2.0.7 on 2018-07-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180722_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bc_hierarchy_1',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bc_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bc_hierarchy_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bc_slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bc_text_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_2_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_2_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_2_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_2_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_2_ps',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_2_sku_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_2_sku_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_2_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_ps',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_sku_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_sku_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bq_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_2_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_2_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_2_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_2_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_2_ps',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_2_sku_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_2_sku_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_2_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_ps',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_sku_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_sku_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wickes_url',
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pack_size',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sku_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sku_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('master_product', 'master_product'), ('compared_product', 'compared_product')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
