# Generated by Django 2.0.7 on 2018-10-20 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_project_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_items',
        ),
        migrations.AddField(
            model_name='project_item',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Project'),
            preserve_default=False,
        ),
    ]
