# Generated by Django 2.0.7 on 2018-07-27 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180724_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant', models.CharField(blank=True, choices=[('basket compare', 'Basket Compare'), ('bq', 'B&Q'), ('homebase', 'Homebase'), ('screwfix', 'Screwfix'), ('selco', 'Selco'), ('toolstation', 'Toolstation'), ('tradepoint', 'Tradepoint'), ('travis perkins', 'Travis Perkins'), ('wickes', 'Wickes')], max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='merchant',
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(default="hi", on_delete=django.db.models.deletion.CASCADE, to='products.Merchant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
