# Generated by Django 2.0.7 on 2018-10-20 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181020_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_item',
            name='item',
        ),
        migrations.AddField(
            model_name='project_item',
            name='item',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_item',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Project'),
        ),
    ]
