# Generated by Django 2.0.7 on 2018-10-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20181020_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_item',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Project'),
        ),
    ]
