# Generated by Django 2.0.7 on 2018-10-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181021_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_item',
            name='item',
        ),
        migrations.AddField(
            model_name='project_item',
            name='item',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
